# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            messageformat.js
tagline:          'ICU MessageFormat for Javascript'
description:      'Gender- and plural-capable messages using ICU MessageFormat'
url:              https://messageformat.github.io
baseurl:          /

author:
  name:           'Alex Sexton & Eemeli Aro'

paginate:         5

# Custom vars
version:          0.3.1

npm:
  link:           https://www.npmjs.com/package/messageformat

github:
  repo:           https://github.com/SlexAxton/messageformat.js
